### ISSUE TITLE
Plugin incompatible with bluemaps

### ISSUE THREAD

**Issue by Inferno5130** [DestinyofYeet/TeamSimplifiedV2#1]
Hello! I was using this plugin along with bluemaps and it caused bluemaps to be unable to load and render more of the map. I was told that the plugin started a while-loop in bluemaps on-enable listener, which never exits.

**Comment by DestinyofYeet** [comment]
Hi! I'm actually surprised that someone uses this. I basically wrote it for a friend.

The idea was, that the rendering of the chunks was on a separate thread to not block the main bluemaps thread.
At the time I wrote it, the code worked and currently I don't have a need for it so I won't fix it. You're welcome to fork the code and fix it though :D
